### PR TITLE
feat: update patterns and remove unused files

### PR DESCRIPTION
**Pull request by thomasguillot**
This PR takes the various patterns to the next level. Making the most of the Editor instead of relying on custom CSS.

e.g

I've also removed a bunch of unused files.

Temp demo: https://speedily-given.wp.build/media-kit/

__How to test__

1- Install this plugin, activate it
2- Go to edit the new Media Kit page created (note: you will need to permanently delete any previously created)
3- Check if it works as expected (please use the block theme for now. if you use the classic theme, the colours will be missing)

### CODE REVIEW

**Comment by dkoo** [comment]
@thomasguillot I'll test this after #1 is merged

**Comment by thomasguillot** [comment]
@dkoo the PR should be up-to-date with the main branch. I hope it didn't break everything 🥺

**Review by dkoo — CHANGES_REQUESTED** [review]
@thomasguillot on a fresh site, when activating the plugin I see this fatal in PHP log:

```
[02-Jul-2024 23:21:00 UTC] PHP Fatal error:  Uncaught Error: Class "PublisherMediaKit\blocks\BlockContext\Tabs" not found in /newspack-repos/publisher-media-kit-for-newspack/publisher-media-kit.php:102
Stack trace:
#0 /var/www/html/wp-admin/includes/plugin.php(2389): include_once()
#1 /var/www/html/wp-admin/includes/plugin.php(675): plugin_sandbox_scrape()
#2 /var/www/html/wp-admin/plugins.php(60): activate_plugin()
#3 {main}
  thrown in /newspack-repos/publisher-media-kit-for-newspack/publisher-media-kit.php on line 102
```

It doesn't seem to affect the content of page itself, though

**Comment by thomasguillot** [comment]
@dkoo For some reason I can't replicate the error.

I noticed in https://github.com/10up/publisher-media-kit/pull/125/files they removed `require_once PUBLISHER_MEDIA_KIT_INC . '/classes/blocks/BlockContext/Tabs.php';`. Do you think this could be related?

**Review by dkoo — APPROVED** [review]
Not seeing the error anymore on JN—I'm going to go ahead and approve.

**Pull request merged**
