### PR TITLE
feat: update tabs and tabs item blocks

### PR DESCRIPTION
**Pull request by thomasguillot**
This PR improves the design of the Tabs and Tabs Item blocks by aligning it more with Newspack Components, particularly the Tab navigation.

It introduces new block icons.

The blocks have been renamed from `10up/blockname` to `newspack/blockname` and have been added to the Newspack category in the Inserter.

The overall experience in the editor has been slightly improved.

Screenshot 2024-06-04 at 14 56 13@2x

Screenshot 2024-06-04 at 14 58 59@2x

Note: The "Media Kit" page that's created automatically will be improved. Right now, I'm just focussing on the blocks.

__How to test:__

1- Experiment with the "old" Media Kit Plugin, particularly the Tabs block.
2- Switch to this branch.
3- Experiment with the new plugin, and more importantly, the blocks.

### CODE REVIEW

**Comment by thomasguillot** [comment]
Tagging @Automattic/newspack-product for review.

**Review by dkoo — CHANGES_REQUESTED** [review]
Nice updates! Only issue I'm seeing is this strange state when adding a new tab item in the editor:

Screenshot 2024-06-17 at 12 52 48 PM

**Comment by thomasguillot** [comment]
@dkoo oh interesting. I was not able to replicate this issue. Are you on WP 6.5 or 6.6? Also, are you using the Block Theme or the Classic Theme?

**Comment by dkoo** [comment]
Oh, I'm on WP 6.6. Could be related...

**Comment by thomasguillot** [comment]
@dkoo issue should be fixed https://github.com/Automattic/publisher-media-kit-for-newspack/pull/1/commits/a0fc682b0b02cdede05512a66055b8b60266a386

Quite frankly I don't know what's creating this... This is very weird... 🤔

**Review by dkoo — APPROVED** [review]
It's still not resolved for me, but I find that changing [this line](https://github.com/Automattic/publisher-media-kit-for-newspack/blob/update/tabs-block/includes/blocks/block-editor/tabs/editor.css#L34) to `top: -4px;` does fix it for me in WP 6.6. Didn't test the effect in WP 6.5.

I don't think this is a blocker as it's a minor style issue that could be fixed after WP 6.6 goes live.

**Comment by thomasguillot** [comment]
Thank you @dkoo. This is such a strange bug! I moved the fix to CSS instead of JS so hopefully it will help 🤞

**Pull request merged**
